services:
  db:
    image: postgres:16-alpine
    container_name: rampup-postgres
    restart: unless-stopped
    networks:
      - rampup
    secrets:
      - db_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USERNAME}
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password

networks:
  rampup:
    name: rampup-network
    driver: bridge

secrets:
  db_password:
    environment: DB_PASSWORD

volumes:
  postgres-data:
    name: rampup-postgres-data
