services:
  labs-rampup:
    image: mcr.microsoft.com/devcontainers/typescript-node:bookworm
    container_name: labs-rampup
    command: sleep infinity
    volumes:
      - ..:/workspaces/rampup:cached

  db:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rampup
      - POSTGRES_USER=rampup
      - POSTGRES_PASSWORD=password