name: "Build"

on:
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build