name: "Build and Push Docker Image"

on:
  workflow_call:
    inputs:
      push:
        default: false
        type: boolean
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  docker:
    name: "Build and Push Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: vinicius507/rampup
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}
      - name: Build and push to Docker
        uses: docker/build-push-action@v6
        with:
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
