on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  e2e-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    container: node:20-bookworm
    needs: [unit-tests]
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: tasks
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:e2e
        env:
          DB_HOST: postgres
          DB_NAME: tasks
          DB_USER: postgres
          DB_PASSWORD: password
