name: "Tests"

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  test-cov:
    name: "Test coverage"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:cov
  e2e-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    container: node:20-bookworm
    needs: [build]
    services:
      db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: rampup
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rampup
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "22.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:e2e
